version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: comments_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: comments_db
    ports:
      - "5432:5432"
    volumes:
      - ./new-postgres-data:/var/lib/postgresql/data
    networks:
      - comments_network

networks:
  comments_network:
    driver: bridge
